apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: pandadatagen
spec:
  maxRetry: 1
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 20
      name: train
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: dkr-creds
          securityContext:
            runAsUser: 1000
          
          containers:
            - name: runner
              imagePullPolicy: Always
              image: mu00120825.eng.monash.edu.au:5021/mazepanda:latest
              command: [python3, maze_panda.py]
              
              workingDir: /app
              env:
                - name: WANDB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: wandb
                      key: api-key
                - name: WANDB_CACHE_DIR
                  value: /home/user

              resources:
                requests:
                  memory: 4Gi
                  cpu: 1000m
                limits:
                  memory: 8Gi
                  cpu: 2000m
              volumeMounts:
                - name: storage
                  mountPath: /mnt/storage
                - name: slow
                  mountPath: /mnt/slow
                - name: slow2
                  mountPath: /mnt/slow2
                - mountPath: /dev/shm
                  name: dshm
          volumes:
            - name: storage
              flexVolume:
                driver: fstab/cifs
                fsType: cifs
                secretRef:
                  name: smb-creds
                options:
                  networkPath: //130.194.128.238/fast
                  mountOptions: dir_mode=0777,file_mode=0777,noperm
            - name: slow2
              flexVolume:
                driver: fstab/cifs
                fsType: cifs
                secretRef:
                  name: smb-creds
                options:
                  networkPath: //130.194.128.238/slow
                  mountOptions: dir_mode=0777,file_mode=0777,noperm
            - name: slow
              nfs:
                server: 130.194.128.238
                path: /mnt/fast/more-users/bryce-rhys

            - name: dshm
              emptyDir:
                medium: Memory